M48
; DRILL file {KiCad 7.0.8} date 2023 November 16, Thursday 17:33:38
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-16T17:33:38+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X4.0748Y-1.8701
X4.0748Y-3.7992
X6.3583Y-1.8701
X6.3583Y-3.7992
T0
M30
